// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDENHB4tujZc12xGWbNYTlVNsJg8xcgGhA',
    appId: '1:132546174553:web:a46dcd4f36c37ce5589b48',
    messagingSenderId: '132546174553',
    projectId: 'chichart-79660',
    authDomain: 'chichart-79660.firebaseapp.com',
    storageBucket: 'chichart-79660.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPktST-CJHwqKROkH4eHZBH-7rwlSVZyI',
    appId: '1:132546174553:android:f27fc01eb1817da5589b48',
    messagingSenderId: '132546174553',
    projectId: 'chichart-79660',
    storageBucket: 'chichart-79660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBounDh253mew4taeSosw_zVP1VYtfYycc',
    appId: '1:132546174553:ios:cb0d765a22e80ce7589b48',
    messagingSenderId: '132546174553',
    projectId: 'chichart-79660',
    storageBucket: 'chichart-79660.appspot.com',
    iosBundleId: 'com.example.chicart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBounDh253mew4taeSosw_zVP1VYtfYycc',
    appId: '1:132546174553:ios:cb0d765a22e80ce7589b48',
    messagingSenderId: '132546174553',
    projectId: 'chichart-79660',
    storageBucket: 'chichart-79660.appspot.com',
    iosBundleId: 'com.example.chicart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDENHB4tujZc12xGWbNYTlVNsJg8xcgGhA',
    appId: '1:132546174553:web:d670cd192b9a858d589b48',
    messagingSenderId: '132546174553',
    projectId: 'chichart-79660',
    authDomain: 'chichart-79660.firebaseapp.com',
    storageBucket: 'chichart-79660.appspot.com',
  );

}